# Generated by Django 4.1.7 on 2023-03-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApnaBazaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(max_length=200)),
                ('product_description', models.TextField(max_length=2000)),
            ],
        ),
    ]
