# Generated by Django 4.1.7 on 2023-03-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApnaBazaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('quantity', models.CharField(max_length=150)),
                ('product_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
