# Generated by Django 4.1.7 on 2023-03-27 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apna_bazaar', '0004_alter_address_mobile_no_alter_address_pin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now=True)),
                ('total', models.CharField(max_length=10000000)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apna_bazaar.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=1000000)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apna_bazaar.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apna_bazaar.apnabazaar')),
            ],
        ),
    ]
