# Generated by Django 4.1.7 on 2023-03-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apna_bazaar', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='apnabazaar',
            name='product_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
