# Generated by Django 4.1.7 on 2023-03-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_of_release',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
