# Generated by Django 4.1.7 on 2023-03-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_date_of_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_of_release',
            field=models.DateTimeField(),
        ),
    ]
